// This file was auto-generated by prisma-generator-typescript-interfaces

export type UserRole = 'ADMIN' | 'STAFF' | 'DOCTOR' | 'OWNER' | 'PATIENT'

export const UserRole = {
	ADMIN: 'ADMIN',
	STAFF: 'STAFF',
	DOCTOR: 'DOCTOR',
	OWNER: 'OWNER',
	PATIENT: 'PATIENT',
} satisfies Record<string, UserRole>

export type EncounterType =
	| 'CONSULTATION'
	| 'VACCINATION'
	| 'SCREENING'
	| 'FOLLOW_UP'
	| 'NUTRITION'
	| 'NEWBORN'
	| 'LACTATION'
	| 'OTHER'

export const EncounterType = {
	CONSULTATION: 'CONSULTATION',
	VACCINATION: 'VACCINATION',
	SCREENING: 'SCREENING',
	FOLLOW_UP: 'FOLLOW_UP',
	NUTRITION: 'NUTRITION',
	NEWBORN: 'NEWBORN',
	LACTATION: 'LACTATION',
	OTHER: 'OTHER',
} satisfies Record<string, EncounterType>

export type EncounterStatus = 'PENDING' | 'COMPLETED' | 'CANCELLED'

export const EncounterStatus = {
	PENDING: 'PENDING',
	COMPLETED: 'COMPLETED',
	CANCELLED: 'CANCELLED',
} satisfies Record<string, EncounterStatus>

export type AvailabilityStatus = 'AVAILABLE' | 'UNAVAILABLE'

export const AvailabilityStatus = {
	AVAILABLE: 'AVAILABLE',
	UNAVAILABLE: 'UNAVAILABLE',
} satisfies Record<string, AvailabilityStatus>

export type GrowthStatus =
	| 'NORMAL'
	| 'OBESE'
	| 'OVERWEIGHT'
	| 'UNDERWEIGHT'
	| 'STUNTED'

export const GrowthStatus = {
	NORMAL: 'NORMAL',
	OBESE: 'OBESE',
	OVERWEIGHT: 'OVERWEIGHT',
	UNDERWEIGHT: 'UNDERWEIGHT',
	STUNTED: 'STUNTED',
} satisfies Record<string, GrowthStatus>

export type AppointmentType =
	| 'CONSULTATION'
	| 'VACCINATION'
	| 'PROCEDURE'
	| 'EMERGENCY'
	| 'CHECKUP'
	| 'FOLLOW_UP'
	| 'FEEDING_SESSION'
	| 'OTHER'

export const AppointmentType = {
	CONSULTATION: 'CONSULTATION',
	VACCINATION: 'VACCINATION',
	PROCEDURE: 'PROCEDURE',
	EMERGENCY: 'EMERGENCY',
	CHECKUP: 'CHECKUP',
	FOLLOW_UP: 'FOLLOW_UP',
	FEEDING_SESSION: 'FEEDING_SESSION',
	OTHER: 'OTHER',
} satisfies Record<string, AppointmentType>

export type Status = 'ACTIVE' | 'INACTIVE' | 'DORMANT'

export const Status = {
	ACTIVE: 'ACTIVE',
	INACTIVE: 'INACTIVE',
	DORMANT: 'DORMANT',
} satisfies Record<string, Status>

export type JOBTYPE = 'FULL' | 'PART'

export const JOBTYPE = {
	FULL: 'FULL',
	PART: 'PART',
} satisfies Record<string, JOBTYPE>

export type Gender = 'MALE' | 'FEMALE'

export const Gender = {
	MALE: 'MALE',
	FEMALE: 'FEMALE',
} satisfies Record<string, Gender>

export type AppointmentStatus =
	| 'PENDING'
	| 'SCHEDULED'
	| 'CANCELLED'
	| 'COMPLETED'
	| 'NO_SHOW'

export const AppointmentStatus = {
	PENDING: 'PENDING',
	SCHEDULED: 'SCHEDULED',
	CANCELLED: 'CANCELLED',
	COMPLETED: 'COMPLETED',
	NO_SHOW: 'NO_SHOW',
} satisfies Record<string, AppointmentStatus>

export type PaymentMethod = 'CASH' | 'CARD' | 'MOBILE'

export const PaymentMethod = {
	CASH: 'CASH',
	CARD: 'CARD',
	MOBILE: 'MOBILE',
} satisfies Record<string, PaymentMethod>

export type PaymentStatus = 'PAID' | 'UNPAID' | 'PARTIAL' | 'REFUNDED'

export const PaymentStatus = {
	PAID: 'PAID',
	UNPAID: 'UNPAID',
	PARTIAL: 'PARTIAL',
	REFUNDED: 'REFUNDED',
} satisfies Record<string, PaymentStatus>

export type ServiceCategory =
	| 'CONSULTATION'
	| 'LAB_TEST'
	| 'VACCINATION'
	| 'PROCEDURE'
	| 'PHARMACY'
	| 'DIAGNOSIS'
	| 'OTHER'

export const ServiceCategory = {
	CONSULTATION: 'CONSULTATION',
	LAB_TEST: 'LAB_TEST',
	VACCINATION: 'VACCINATION',
	PROCEDURE: 'PROCEDURE',
	PHARMACY: 'PHARMACY',
	DIAGNOSIS: 'DIAGNOSIS',
	OTHER: 'OTHER',
} satisfies Record<string, ServiceCategory>

export type MeasurementType = 'Weight' | 'Height' | 'HeadCircumference'

export const MeasurementType = {
	Weight: 'Weight',
	Height: 'Height',
	HeadCircumference: 'HeadCircumference',
} satisfies Record<string, MeasurementType>

export type ChartType = 'WFA' | 'HFA' | 'HcFA'

export const ChartType = {
	WFA: 'WFA',
	HFA: 'HFA',
	HcFA: 'HcFA',
} satisfies Record<string, ChartType>

export type ReminderMethod = 'EMAIL' | 'SMS'

export const ReminderMethod = {
	EMAIL: 'EMAIL',
	SMS: 'SMS',
} satisfies Record<string, ReminderMethod>

export type ReminderStatus = 'SENT' | 'FAILED' | 'PENDING'

export const ReminderStatus = {
	SENT: 'SENT',
	FAILED: 'FAILED',
	PENDING: 'PENDING',
} satisfies Record<string, ReminderStatus>

export type NotificationType =
	| 'APPOINTMENT_REMINDER'
	| 'BILLING'
	| 'GENERAL'
	| 'SECURITY'

export const NotificationType = {
	APPOINTMENT_REMINDER: 'APPOINTMENT_REMINDER',
	BILLING: 'BILLING',
	GENERAL: 'GENERAL',
	SECURITY: 'SECURITY',
} satisfies Record<string, NotificationType>

export type FeedingType = 'BREAST' | 'FORMULA' | 'MIXED'

export const FeedingType = {
	BREAST: 'BREAST',
	FORMULA: 'FORMULA',
	MIXED: 'MIXED',
} satisfies Record<string, FeedingType>

export type DevelopmentStatus = 'NORMAL' | 'DELAYED' | 'ADVANCED' | 'CONCERNING'

export const DevelopmentStatus = {
	NORMAL: 'NORMAL',
	DELAYED: 'DELAYED',
	ADVANCED: 'ADVANCED',
	CONCERNING: 'CONCERNING',
} satisfies Record<string, DevelopmentStatus>

export type ImmunizationStatus =
	| 'COMPLETED'
	| 'PENDING'
	| 'OVERDUE'
	| 'DELAYED'
	| 'EXEMPTED'

export const ImmunizationStatus = {
	COMPLETED: 'COMPLETED',
	PENDING: 'PENDING',
	OVERDUE: 'OVERDUE',
	DELAYED: 'DELAYED',
	EXEMPTED: 'EXEMPTED',
} satisfies Record<string, ImmunizationStatus>

export type DosageUnit =
	| 'MG'
	| 'ML'
	| 'TABLET'
	| 'MCG'
	| 'G'
	| 'IU'
	| 'DROP'
	| 'SPRAY'
	| 'PUFF'
	| 'UNIT'

export const DosageUnit = {
	MG: 'MG',
	ML: 'ML',
	TABLET: 'TABLET',
	MCG: 'MCG',
	G: 'G',
	IU: 'IU',
	DROP: 'DROP',
	SPRAY: 'SPRAY',
	PUFF: 'PUFF',
	UNIT: 'UNIT',
} satisfies Record<string, DosageUnit>

export type DrugRoute =
	| 'IV'
	| 'PO'
	| 'IM'
	| 'SC'
	| 'TOPICAL'
	| 'INHALED'
	| 'RECTAL'
	| 'SUBLINGUAL'
	| 'BUCCAL'
	| 'TRANSDERMAL'

export const DrugRoute = {
	IV: 'IV',
	PO: 'PO',
	IM: 'IM',
	SC: 'SC',
	TOPICAL: 'TOPICAL',
	INHALED: 'INHALED',
	RECTAL: 'RECTAL',
	SUBLINGUAL: 'SUBLINGUAL',
	BUCCAL: 'BUCCAL',
	TRANSDERMAL: 'TRANSDERMAL',
} satisfies Record<string, DrugRoute>

export type LabStatus = 'PENDING' | 'COMPLETED' | 'REVIEWED' | 'CANCELLED'

export const LabStatus = {
	PENDING: 'PENDING',
	COMPLETED: 'COMPLETED',
	REVIEWED: 'REVIEWED',
	CANCELLED: 'CANCELLED',
} satisfies Record<string, LabStatus>

export type AccessLevel = 'STANDARD' | 'SENSITIVE' | 'RESTRICTED'

export const AccessLevel = {
	STANDARD: 'STANDARD',
	SENSITIVE: 'SENSITIVE',
	RESTRICTED: 'RESTRICTED',
} satisfies Record<string, AccessLevel>

export type AccessType = 'VIEW' | 'EDIT' | 'PRINT' | 'EXPORT'

export const AccessType = {
	VIEW: 'VIEW',
	EDIT: 'EDIT',
	PRINT: 'PRINT',
	EXPORT: 'EXPORT',
} satisfies Record<string, AccessType>

export type SavedFilterType =
	| 'medical_records'
	| 'patients'
	| 'appointments'
	| 'lab_tests'

export const SavedFilterType = {
	medical_records: 'medical_records',
	patients: 'patients',
	appointments: 'appointments',
	lab_tests: 'lab_tests',
} satisfies Record<string, SavedFilterType>

export type TrainingFileStatus =
	| 'PENDING'
	| 'PROCESSING'
	| 'COMPLETED'
	| 'FAILED'

export const TrainingFileStatus = {
	PENDING: 'PENDING',
	PROCESSING: 'PROCESSING',
	COMPLETED: 'COMPLETED',
	FAILED: 'FAILED',
} satisfies Record<string, TrainingFileStatus>

export type KnowledgeBaseStatus = 'PENDING' | 'CREATING' | 'READY' | 'ERROR'

export const KnowledgeBaseStatus = {
	PENDING: 'PENDING',
	CREATING: 'CREATING',
	READY: 'READY',
	ERROR: 'ERROR',
} satisfies Record<string, KnowledgeBaseStatus>

export type TrainingWebsiteStatus =
	| 'PENDING'
	| 'PROCESSING'
	| 'COMPLETED'
	| 'FAILED'

export const TrainingWebsiteStatus = {
	PENDING: 'PENDING',
	PROCESSING: 'PROCESSING',
	COMPLETED: 'COMPLETED',
	FAILED: 'FAILED',
} satisfies Record<string, TrainingWebsiteStatus>

export type TwoFactor = {
	id: string
	secret: string
	backupCodes: string
	userId: string
	user?: User
}

export type User = {
	id?: string
	email: string
	name?: string | null
	emailVerified?: boolean
	image?: string | null
	bio?: string | null
	timezone?: string | null
	language?: string | null
	createdAt?: Date
	updatedAt: Date
	isAdmin?: boolean
	banned?: boolean
	betterAuthId?: string | null
	sessions?: Session[]
	accounts?: Account[]
	invitations?: clinicInvitation[]
	notifications?: Notification[]
	auditLogs?: AuditLog[]
	twoFactorAuth?: TwoFactorAuth | null
	passkeys?: Passkey[]
	apiKeys?: APIKey[]
	twoFactors?: TwoFactor[]
	files?: File[]
	folders?: Folder[]
	clinicId?: string | null
	role?: UserRole | null
	doctor?: Doctor | null
	staff?: Staff | null
	guardians?: Guardian[]
	medicalRecordAccesses?: MedicalRecordAccess[]
	userQuotas?: UserQuota[]
	patientAsUser?: Patient | null
	patientsAsDoctor?: Patient[]
	patientsCreated?: Patient[]
	fileStorages?: FileStorage[]
	banReason?: string | null
	banExpires?: Date | null
	phone?: string | null
	clinicinvitations?: OrganizationInvitation[]
	clinicMembers?: ClinicMember[]
	growthRecords?: GrowthRecord[]
	_count?: {
		sessions?: number
		accounts?: number
		invitations?: number
		notifications?: number
		auditLogs?: number
		passkeys?: number
		apiKeys?: number
		twoFactors?: number
		files?: number
		folders?: number
		guardians?: number
		medicalRecordAccesses?: number
		userQuotas?: number
		patientsAsDoctor?: number
		patientsCreated?: number
		fileStorages?: number
		clinicinvitations?: number
		clinicMembers?: number
		growthRecords?: number
	}
}

export type Session = {
	id?: string
	userId: string
	user?: User
	token: string
	expiresAt: Date
	ipAddress?: string | null
	userAgent?: string | null
	deviceName?: string | null
	createdAt?: Date
	updatedAt: Date
	lastActiveAt?: Date
}

export type Account = {
	id?: string
	userId: string
	user?: User
	accountId: string
	providerId: string
	accessToken?: string | null
	refreshToken?: string | null
	idToken?: string | null
	expiresAt?: Date | null
	password?: string | null
	createdAt?: Date
	updatedAt: Date
	accessTokenExpiresAt?: Date | null
	refreshTokenExpiresAt?: Date | null
	scope?: string | null
}

export type Verification = {
	id?: string
	identifier: string
	value: string
	expiresAt: Date
	createdAt?: Date
	updatedAt: Date
}

export type ClinicMember = {
	id?: string
	clinicId: string
	clinic?: Clinic
	userId: string
	user?: User
	roleId: string
	role?: Role
	joinedAt?: Date
	createdAt?: Date
	updatedAt: Date
	organizations?: Organization[]
	_count?: {
		organizations?: number
	}
}

export type Role = {
	id?: string
	clinicId: string
	clinic?: Clinic
	name: string
	description?: string | null
	permissions: Record<string, unknown>
	isSystem?: boolean
	createdAt?: Date
	updatedAt: Date
	members?: ClinicMember[]
	invitations?: clinicInvitation[]
	_count?: {
		members?: number
		invitations?: number
	}
}

export type clinicInvitation = {
	id?: string
	clinicId: string
	clinic?: Clinic
	email?: string | null
	invitedById: string
	invitedBy?: User
	roleId: string
	role?: Role
	token: string
	type?: string
	maxUses?: number | null
	usedCount?: number
	status?: string
	expiresAt: Date
	acceptedAt?: Date | null
	createdAt?: Date
}

export type Notification = {
	id?: string
	userId: string
	user?: User
	title: string
	message: string
	type?: string
	read?: boolean
	readAt?: Date | null
	createdAt?: Date
}

export type TwoFactorAuth = {
	id?: string
	userId: string
	user?: User
	secret: string
	enabled?: boolean
	backupCodes: string[]
	createdAt?: Date
	updatedAt: Date
}

export type Passkey = {
	id?: string
	userId: string
	user?: User
	credentialId: string
	publicKey: string
	counter?: number
	deviceName?: string | null
	lastUsedAt?: Date | null
	createdAt?: Date
	name?: string | null
	credentialID: string
	deviceType: string
	backedUp: boolean
	transports?: string | null
	aaguid?: string | null
}

export type SystemSettings = {
	id?: string
	clinicId?: string | null
	clinic?: Clinic | null
	theme?: string
	maintenanceMode?: boolean
	maintenanceMessage?: string | null
	maintenanceStartedAt?: Date | null
	maintenanceEndTime?: Date | null
	updatedAt: Date
	updatedBy?: string | null
}

export type APIKey = {
	id?: string
	clinicId: string
	clinic?: Clinic
	name: string
	key: string
	hashedKey: string
	lastUsedAt?: Date | null
	expiresAt?: Date | null
	createdById: string
	createdBy?: User
	createdAt?: Date
}

export type Settings = {
	id?: string
	key: string
	value: string
	createdAt?: Date
	updatedAt: Date
}

export type AuditLog = {
	id?: string
	userId?: string | null
	user?: User | null
	action: string
	level: string
	details?: string | null
	resource?: string | null
	resourceId?: string | null
	metadata?: Record<string, unknown> | null
	ipAddress?: string | null
	userAgent?: string | null
	createdAt?: Date
	recordId?: string | null
	model: string
	clinic?: Clinic | null
	message?: string | null
	timestamp?: Date
	clinicId?: string | null
	updatedAt: Date
}

export type Organization = {
	id: string
	name: string
	slug: string
	logo?: string | null
	createdAt: Date
	metadata?: string | null
	clinicmembers?: ClinicMember[]
	clinicinvitations?: OrganizationInvitation[]
	_count?: {
		clinicmembers?: number
		clinicinvitations?: number
	}
}

export type OrganizationInvitation = {
	id: string
	clinicId: string
	organization?: Organization
	email: string
	role?: string | null
	status?: string
	expiresAt: Date
	createdAt?: Date
	inviterId: string
	user?: User
}

export type Todo = {
	id?: number
	text: string
	completed?: boolean
}

export type Feature = {
	id?: string
	clinicId: string
	clinic?: Clinic
	title: string
	description?: string | null
	icon?: string | null
	color?: string | null
	order?: number | null
	isActive?: boolean
}

export type File = {
	id: string
	slug: string
	userId: string
	folderId?: string | null
	filename: string
	searchText?: string
	size: number
	mimeType: string
	createdAt?: Date
	updatedAt: Date
	user?: User
	folder?: Folder | null
}

export type Folder = {
	id: string
	userId: string
	name: string
	parentId?: string | null
	createdAt?: Date
	updatedAt: Date
	user?: User
	parent?: Folder | null
	subfolders?: Folder[]
	files?: File[]
	_count?: {
		subfolders?: number
		files?: number
	}
}

export type Clinic = {
	id?: string
	name: string
	email?: string | null
	slug?: string | null
	description?: string | null
	archived?: boolean
	archivedAt?: Date | null
	archivedBy?: string | null
	createdAt?: Date
	updatedAt: Date
	timezone?: string | null
	address?: string | null
	phone?: string | null
	logo?: string | null
	deletedAt?: Date | null
	isDeleted?: boolean | null
	doctors?: Doctor[]
	patients?: Patient[]
	appointments?: Appointment[]
	medicalRecords?: MedicalRecords[]
	clinicSettings?: ClinicSetting[]
	prescriptions?: Prescription[]
	payments?: Payment[]
	encounters?: Diagnosis[]
	services?: Service[]
	auditLogs?: AuditLog[]
	staffs?: Staff[]
	expenses?: Expense[]
	workingDays?: WorkingDays[]
	features?: Feature[]
	systemSettings?: SystemSettings[]
	clinicMembers?: ClinicMember[]
	ratings?: Rating[]
	growthRecords?: GrowthRecord[]
	roles?: Role[]
	invitations?: clinicInvitation[]
	apiKeys?: APIKey[]
	fileStorages?: FileStorage[]
	knowledgeBase?: KnowledgeBase | null
	agents?: Agent[]
	_count?: {
		doctors?: number
		patients?: number
		appointments?: number
		medicalRecords?: number
		clinicSettings?: number
		prescriptions?: number
		payments?: number
		encounters?: number
		services?: number
		auditLogs?: number
		staffs?: number
		expenses?: number
		workingDays?: number
		features?: number
		systemSettings?: number
		clinicMembers?: number
		ratings?: number
		growthRecords?: number
		roles?: number
		invitations?: number
		apiKeys?: number
		fileStorages?: number
		agents?: number
	}
}

export type Doctor = {
	id?: string
	email?: string | null
	name: string
	userId?: string | null
	clinicId?: string | null
	specialty: string
	licenseNumber?: string | null
	phone?: string | null
	address?: string | null
	department?: string | null
	img?: string | null
	colorCode?: string | null
	availabilityStatus?: AvailabilityStatus | null
	availableFromWeekDay?: number | null
	availableToWeekDay?: number | null
	isActive?: boolean | null
	status?: Status | null
	availableFromTime?: string | null
	availableToTime?: string | null
	type?: JOBTYPE
	createdAt?: Date
	updatedAt: Date
	appointmentPrice: Decimal
	role?: UserRole | null
	deletedAt?: Date | null
	isDeleted?: boolean | null
	user?: User | null
	clinic?: Clinic | null
	workingDays?: WorkingDays[]
	appointments?: Appointment[]
	encounter?: Diagnosis[]
	Prescription?: Prescription[]
	medicalRecords?: MedicalRecords[]
	ratings?: Rating[]
	fileStorages?: FileStorage[]
	_count?: {
		workingDays?: number
		appointments?: number
		encounter?: number
		Prescription?: number
		medicalRecords?: number
		ratings?: number
		fileStorages?: number
	}
}

export type WorkingDays = {
	id?: number
	doctorId: string
	clinicId: string
	day: string
	startTime: string
	closeTime: string
	doctor?: Doctor
	clinic?: Clinic
	createdAt?: Date
	updatedAt: Date
}

export type Staff = {
	id?: string
	email?: string | null
	name: string
	phone?: string | null
	userId?: string | null
	user?: User | null
	clinicId?: string | null
	clinic?: Clinic | null
	address: string
	department?: string | null
	img?: string | null
	licenseNumber?: string | null
	colorCode?: string | null
	hireDate?: Date | null
	salary?: number | null
	role: UserRole
	status?: Status | null
	createdAt?: Date
	updatedAt: Date
	deletedAt?: Date | null
	isActive?: boolean | null
	immunizations?: Immunization[]
	_count?: {
		immunizations?: number
	}
}

export type Payment = {
	id?: string
	clinicId?: string | null
	clinic?: Clinic | null
	billId?: string | null
	patientId?: string | null
	appointmentId: string
	billDate: Date
	paymentDate?: Date | null
	discount?: Decimal | null
	totalAmount?: Decimal | null
	amountPaid?: Decimal | null
	patient?: Patient | null
	appointment?: Appointment | null
	amount?: Decimal | null
	status?: PaymentStatus
	insurance?: string | null
	insuranceId?: string | null
	serviceDate?: Date | null
	dueDate?: Date | null
	paidDate?: Date | null
	notes?: string | null
	deletedAt?: Date | null
	isDeleted?: boolean | null
	paymentMethod?: PaymentMethod
	receiptNumber?: number
	bills?: PatientBill[]
	createdAt?: Date
	updatedAt: Date
	_count?: {
		bills?: number
	}
}

export type Reminder = {
	id?: string
	appointmentId: string
	appointment?: Appointment
	method: ReminderMethod
	sentAt: Date
	status: ReminderStatus
}

export type PatientBill = {
	id?: string
	billId: string
	serviceId: string
	serviceDate: Date
	quantity: number
	unitCost?: Decimal | null
	totalCost?: Decimal | null
	service?: Service
	payment?: Payment
	createdAt?: Date
	updatedAt: Date
}

export type Service = {
	id?: string
	serviceName: string
	description: string
	price: Decimal
	labtest?: LabTest[]
	bills?: PatientBill[]
	category?: ServiceCategory | null
	duration?: number | null
	isAvailable?: boolean | null
	clinicId?: string | null
	status?: Status | null
	clinic?: Clinic | null
	icon?: string | null
	color?: string | null
	appointments?: Appointment[]
	createdAt?: Date
	updatedAt: Date
	deletedAt?: Date | null
	isDeleted?: boolean | null
	_count?: {
		labtest?: number
		bills?: number
		appointments?: number
	}
}

export type ClinicSetting = {
	id?: string
	clinicId: string
	clinic?: Clinic
	openingTime: string
	closingTime: string
	workingDays: string[]
	defaultAppointmentDuration?: number
	requireEmergencyContact?: boolean
	createdAt?: Date
	updatedAt: Date
}

export type WHOGrowthStandard = {
	id?: string
	ageInMonths?: number | null
	ageDays: number
	gender: Gender
	chartType?: ChartType | null
	measurementType?: MeasurementType | null
	lValue?: number | null
	mValue?: number | null
	sValue?: number | null
	sd0?: number | null
	sd1neg?: number | null
	sd1pos?: number | null
	sd2neg?: number | null
	sd2pos?: number | null
	sd3neg?: number | null
	sd3pos?: number | null
	sd4neg?: number | null
	sd4pos?: number | null
	createdAt?: Date
	updatedAt: Date
}

export type Rating = {
	id?: number
	clinicId?: string | null
	clinic?: Clinic | null
	staffId?: string | null
	patientId?: string | null
	rating: number
	comment?: string | null
	doctor?: Doctor | null
	patient?: Patient | null
	createdAt?: Date
	updatedAt: Date
}

export type Prescription = {
	id?: string
	medicalRecordId: string
	doctorId?: string | null
	patientId: string
	encounterId: string
	encounter?: Diagnosis
	medicationName?: string | null
	instructions?: string | null
	issuedDate?: Date
	endDate?: Date | null
	status?: string
	medicalRecord?: MedicalRecords
	doctor?: Doctor | null
	patient?: Patient
	clinicId?: string | null
	clinic?: Clinic | null
	createdAt?: Date
	updatedAt: Date
	prescribedItems?: PrescribedItem[]
	_count?: {
		prescribedItems?: number
	}
}

export type Drug = {
	id?: string
	name: string
	guidelines?: DoseGuideline[]
	createdAt?: Date
	updatedAt: Date
	prescribedItems?: PrescribedItem[]
	_count?: {
		guidelines?: number
		prescribedItems?: number
	}
}

export type DoseGuideline = {
	id?: string
	drugId: string
	route: string
	clinicalIndication: string
	minDosePerKg?: number | null
	maxDosePerKg?: number | null
	doseUnit?: string | null
	frequencyDays?: string | null
	gestationalAgeWeeksMin?: number | null
	gestationalAgeWeeksMax?: number | null
	postNatalAgeDaysMin?: number | null
	postNatalAgeDaysMax?: number | null
	maxDosePer24h?: number | null
	stockConcentrationMgMl?: number | null
	finalConcentrationMgMl?: number | null
	minInfusionTimeMin?: number | null
	compatibilityDiluent?: string | null
	createdAt?: Date
	updatedAt: Date
	drug?: Drug
}

export type PrescribedItem = {
	id?: string
	prescriptionId: string
	drugId: string
	dosageValue: number
	dosageUnit: DosageUnit
	frequency: string
	duration: string
	instructions?: string | null
	drugRoute?: DrugRoute | null
	prescription?: Prescription
	drug?: Drug
	createdAt?: Date
	updatedAt: Date
}

export type Guardian = {
	id?: string
	patientId: string
	userId: string
	relation: string
	isPrimary?: boolean
	phone?: string | null
	email?: string | null
	patient?: Patient
	user?: User
}

export type Patient = {
	id?: string
	clinicId: string
	userId: string
	email?: string | null
	phone?: string | null
	emergencyContactNumber?: string | null
	firstName: string
	lastName: string
	dateOfBirth: Date
	ageMonths?: number | null
	ageDays?: number | null
	gender?: Gender
	maritalStatus?: string | null
	nutritionalStatus?: string | null
	address?: string | null
	emergencyContactName?: string | null
	relation?: string | null
	allergies?: string | null
	medicalConditions?: string | null
	medicalHistory?: string | null
	image?: string | null
	colorCode?: string | null
	role?: UserRole | null
	status?: Status | null
	isActive?: boolean | null
	deletedAt?: Date | null
	isDeleted?: boolean | null
	createdById?: string | null
	updatedById?: string | null
	bloodGroup?: string | null
	createdAt?: Date
	updatedAt: Date
	clinic?: Clinic
	user?: User
	createdBy?: User | null
	appointments?: Appointment[]
	medicalRecords?: MedicalRecords[]
	encounters?: Diagnosis[]
	immunizations?: Immunization[]
	vitalSigns?: VitalSigns[]
	feedingLogs?: FeedingLog[]
	prescriptions?: Prescription[]
	ratings?: Rating[]
	developmentalChecks?: DevelopmentalCheck[]
	developmentalMilestones?: DevelopmentalMilestone[]
	growthRecords?: GrowthRecord[]
	payments?: Payment[]
	guardians?: Guardian[]
	doctorId?: string | null
	doctor?: User | null
	fileStorages?: FileStorage[]
	_count?: {
		appointments?: number
		medicalRecords?: number
		encounters?: number
		immunizations?: number
		vitalSigns?: number
		feedingLogs?: number
		prescriptions?: number
		ratings?: number
		developmentalChecks?: number
		developmentalMilestones?: number
		growthRecords?: number
		payments?: number
		guardians?: number
		fileStorages?: number
	}
}

export type Appointment = {
	id?: string
	patientId: string
	doctorId: string
	serviceId?: string | null
	doctorSpecialty?: string | null
	clinicId: string
	appointmentDate: Date
	time?: string | null
	appointmentPrice?: Decimal | null
	status?: AppointmentStatus | null
	type: AppointmentType
	note?: string | null
	reason?: string | null
	deletedAt?: Date | null
	isDeleted?: boolean | null
	createdAt?: Date
	updatedAt: Date
	duration?: number | null
	patient?: Patient
	doctor?: Doctor
	clinic?: Clinic
	service?: Service | null
	bills?: Payment[]
	medical?: MedicalRecords[]
	reminders?: Reminder[]
	encounters?: Diagnosis[]
	_count?: {
		bills?: number
		medical?: number
		reminders?: number
		encounters?: number
	}
}

export type MedicalRecords = {
	id?: string
	patientId: string
	appointmentId: string
	doctorId?: string | null
	clinicId: string
	diagnosis?: string | null
	symptoms?: string | null
	treatmentPlan?: string | null
	labRequest?: string | null
	notes?: string | null
	attachments?: string | null
	followUpDate?: Date | null
	deletedAt?: Date | null
	isDeleted?: boolean | null
	createdAt?: Date
	updatedAt: Date
	patient?: Patient | null
	appointment?: Appointment
	doctor?: Doctor | null
	clinic?: Clinic
	labTest?: LabTest[]
	immunizations?: Immunization[]
	prescriptions?: Prescription[]
	vitalSigns?: VitalSigns[]
	encounter?: Diagnosis[]
	growthRecords?: GrowthRecord[]
	subjective?: string | null
	objective?: string | null
	assessment?: string | null
	plan?: string | null
	isConfidential?: boolean
	accessLevel?: AccessLevel
	lastAccessedAt?: Date | null
	lastAccessedBy?: string | null
	accessLogs?: MedicalRecordAccess[]
	_count?: {
		labTest?: number
		immunizations?: number
		prescriptions?: number
		vitalSigns?: number
		encounter?: number
		growthRecords?: number
		accessLogs?: number
	}
}

export type MedicalRecordAccess = {
	id?: string
	recordId: string
	record?: MedicalRecords
	userId: string
	user?: User
	accessType: AccessType
	purpose?: string | null
	ipAddress?: string | null
	userAgent?: string | null
	accessedAt?: Date
}

export type Diagnosis = {
	id?: string
	patientId: string
	doctorId: string
	clinicId?: string | null
	appointmentId?: string | null
	medicalId: string
	date?: Date
	type?: string | null
	diagnosis?: string | null
	treatment?: string | null
	notes?: string | null
	symptoms: string
	prescribedMedications?: string | null
	followUpPlan?: string | null
	deletedAt?: Date | null
	isDeleted?: boolean | null
	createdAt?: Date
	updatedAt: Date
	status?: EncounterStatus | null
	typeOfEncounter?: EncounterType | null
	patient?: Patient
	doctor?: Doctor
	clinic?: Clinic | null
	appointment?: Appointment | null
	medical?: MedicalRecords
	vitalSigns?: VitalSigns[]
	prescriptions?: Prescription[]
	_count?: {
		vitalSigns?: number
		prescriptions?: number
	}
}

export type VitalSigns = {
	id?: string
	patientId: string
	medicalId: string
	encounterId?: string | null
	recordedAt?: Date
	bodyTemperature?: number | null
	systolic?: number | null
	diastolic?: number | null
	heartRate?: number | null
	respiratoryRate?: number | null
	oxygenSaturation?: number | null
	height?: number | null
	weight?: number | null
	bmi?: number | null
	gender?: Gender | null
	notes?: string | null
	createdAt?: Date
	updatedAt: Date
	ageDays?: number | null
	ageMonths?: number | null
	patient?: Patient
	medical?: MedicalRecords
	encounter?: Diagnosis | null
	growthRecords?: GrowthRecord[]
	_count?: {
		growthRecords?: number
	}
}

export type GrowthRecord = {
	id?: string
	patientId: string
	clinicId?: string | null
	clinic?: Clinic | null
	gender?: Gender | null
	medicalId?: string | null
	vitalSignsId?: string | null
	ageDays?: number | null
	ageMonths?: number | null
	ageYears?: number | null
	percentile?: Decimal | null
	zScore?: Decimal | null
	headCircumference?: Decimal | null
	bmi?: Decimal | null
	weightForAgeZ?: Decimal | null
	heightForAgeZ?: Decimal | null
	bmiForAgeZ?: Decimal | null
	hcForAgeZ?: Decimal | null
	weight?: number | null
	height?: number | null
	notes?: string | null
	growthStatus?: GrowthStatus | null
	date: Date
	recordedAt?: Date | null
	createdAt?: Date
	updatedAt: Date
	classification?: string | null
	deletedAt?: Date | null
	measurementType?: MeasurementType | null
	patient?: Patient
	vitalSigns?: VitalSigns | null
	medical?: MedicalRecords | null
	recordedBy?: User | null
	recordedById?: string | null
}

export type Immunization = {
	id?: string
	patientId: string
	vaccine: string
	date: Date
	dose?: string | null
	lotNumber?: string | null
	administeredByStaffId?: string | null
	notes?: string | null
	createdAt?: Date
	deletedAt?: Date | null
	isDeleted?: boolean | null
	status?: ImmunizationStatus | null
	updatedAt: Date
	isOverDue?: boolean | null
	daysOverDue?: number | null
	patient?: Patient
	administeredBy?: Staff | null
	medicalRecords?: MedicalRecords[]
	_count?: {
		medicalRecords?: number
	}
}

export type ConfigStore = {
	key: string
	value: string
}

export type UserQuota = {
	userId: string
	quota?: number
	usedQuota?: number
	fileCount?: number
	fileCountQuota?: number
	inviteCount?: number
	inviteQuota?: number
	updatedAt?: Date
	user?: User
}

export type LabTest = {
	id?: string
	recordId: string
	serviceId: string
	testDate: Date
	result: string
	status: LabStatus
	notes?: string | null
	createdAt?: Date
	updatedAt: Date
	medicalRecord?: MedicalRecords
	service?: Service
}

export type FeedingLog = {
	id?: string
	patientId: string
	patient?: Patient
	date?: Date
	type: FeedingType
	duration?: number | null
	amount?: number | null
	breast?: string | null
	notes?: string | null
}

export type DevelopmentalMilestone = {
	id?: number
	patientId: string
	milestone: string
	ageAchieved: string
	dateRecorded: Date
	notes?: string | null
	createdBy?: string | null
	updatedBy?: string | null
	patient?: Patient
	createdAt?: Date
	updatedAt: Date
}

export type DevelopmentalCheck = {
	id?: number
	patientId: string
	checkDate: Date
	ageMonths: number
	motorSkills: DevelopmentStatus
	languageSkills: DevelopmentStatus
	socialSkills: DevelopmentStatus
	cognitiveSkills: DevelopmentStatus
	milestonesMet?: string | null
	milestonesPending?: string | null
	concerns?: string | null
	recommendations?: string | null
	patient?: Patient
	createdAt?: Date
	updatedAt: Date
}

export type VaccineSchedule = {
	id?: number
	vaccineName: string
	recommendedAge: string
	dosesRequired: number
	minimumInterval?: number | null
	isMandatory?: boolean
	description?: string | null
	createdAt?: Date
	updatedAt: Date
	ageInDaysMin?: number | null
	ageInDaysMax?: number | null
}

export type Expense = {
	id?: string
	clinicId: string
	subCategoryId: string
	amount: Decimal
	date: Date
	description?: string | null
	createdAt?: Date
	updatedAt: Date
	clinic?: Clinic
	subCategory?: ExpenseSubCategory
}

export type ExpenseCategory = {
	id?: string
	name: string
	color?: string | null
	subCategories?: ExpenseSubCategory[]
	_count?: {
		subCategories?: number
	}
}

export type ExpenseSubCategory = {
	id?: string
	name: string
	color?: string | null
	categoryId: string
	category?: ExpenseCategory
	expenses?: Expense[]
	_count?: {
		expenses?: number
	}
}

export type FileStorage = {
	id?: string
	fileName: string
	filePath: string
	fileType?: string | null
	fileSize?: number | null
	mimeType?: string | null
	isSecure?: boolean
	accessToken?: string | null
	tokenExpiry?: Date | null
	description?: string | null
	metadata?: Record<string, unknown> | null
	url?: string | null
	clinicId?: string | null
	clinic?: Clinic | null
	userId?: string | null
	user?: User | null
	createdAt?: Date
	updatedAt: Date
	status?: string | null
	uploadExpiresAt?: Date | null
	doctorId?: string | null
	doctor?: Doctor | null
	patientId?: string | null
	patient?: Patient | null
	trainingFiles?: TrainingFile[]
	_count?: {
		trainingFiles?: number
	}
}

export type TrainingFile = {
	id?: string
	knowledgeBaseId: string
	knowledgeBase?: KnowledgeBase
	fileStorageId: string
	fileStorage?: FileStorage
	status?: TrainingFileStatus
	errorMessage?: string | null
	processedAt?: Date | null
	createdAt?: Date
	updatedAt: Date
}

export type KnowledgeBase = {
	id?: string
	clinicId: string
	clinic?: Clinic
	name: string
	description?: string | null
	vectorStoreId?: string | null
	status?: KnowledgeBaseStatus
	createdAt?: Date
	updatedAt: Date
	agents?: Agent[]
	trainingFiles?: TrainingFile[]
	trainingWebsites?: TrainingWebsite[]
	_count?: {
		agents?: number
		trainingFiles?: number
		trainingWebsites?: number
	}
}

export type TrainingWebsite = {
	id?: string
	knowledgeBaseId: string
	knowledgeBase?: KnowledgeBase
	url: string
	status?: TrainingWebsiteStatus
	errorMessage?: string | null
	processedAt?: Date | null
	createdAt?: Date
	updatedAt: Date
}

export type Agent = {
	id?: string
	clinicId: string
	clinic?: Clinic
	knowledgeBaseId?: string | null
	knowledgeBase?: KnowledgeBase | null
	name: string
	description?: string | null
	systemPrompt?: string | null
	model?: string
	temperature?: number
	maxTokens?: number | null
	isActive?: boolean
	createdAt?: Date
	updatedAt: Date
}

export type ClinicDashboardMV = {
	clinicId: string
	clinicName: string
	totalAppointments: number
	todayAppointments: number
	upcomingAppointments: number
	completedAppointments: number
	totalPatients: number
	activePatients: number
	newPatientsThisMonth: number
	monthlyRevenue: number
	pendingPayments: number
	totalRevenue: number
	activeDoctors: number
	averageDoctorRating: number
	immunizationsDue: number
	growthChecksPending: number
	totalStaff: number
	updatedAt: Date
}

export type PatientOverviewMV = {
	patientId: string
	patientPublicId: string
	fullName: string
	dateOfBirth?: Date | null
	ageMonths?: number | null
	gender?: string | null
	bloodGroup?: string | null
	medicalRecordNumber: string
	phone?: string | null
	email?: string | null
	address?: string | null
	allergies?: string | null
	medicalConditions?: string | null
	primaryCarePhysician?: string | null
	totalAppointments: number
	lastAppointmentDate?: Date | null
	upcomingAppointments: number
	totalDiagnosis: number
	totalPrescriptions: number
	activePrescriptions: number
	totalImmunizations: number
	pendingImmunizations: number
	lastWeight?: number | null
	lastHeight?: number | null
	lastGrowthCheck?: Date | null
	primaryGuardian?: string | null
	guardianPhone?: string | null
	clinicId: string
	updatedAt: Date
}

export type DoctorPerformanceMV = {
	doctorId: string
	doctorPublicId: string
	name: string
	specialty?: string | null
	email?: string | null
	phone?: string | null
	rating?: number | null
	yearsOfExperience?: number | null
	totalAppointments: number
	appointmentsThisMonth: number
	completedAppointments: number
	cancellationRate: number
	totalPatients: number
	newPatientsThisMonth: number
	totalRevenue: number
	monthlyRevenue: number
	totalPrescriptions: number
	activePrescriptions: number
	averagePatientRating: number
	totalRatings: number
	averagePatientsPerDay: number
	utilizationRate: number
	clinicId: string
	updatedAt: Date
}

export type FinancialOverviewMV = {
	clinicId: string
	clinicName: string
	currentMonthRevenue: number
	previousMonthRevenue: number
	consultationRevenue: number
	procedureRevenue: number
	labRevenue: number
	vaccinationRevenue: number
	totalRevenue: number
	paidAmount: number
	pendingAmount: number
	totalExpenses: number
	payrollExpenses: number
	medicalSupplyExpenses: number
	facilityExpenses: number
	netProfit: number
	profitMargin: number
	topService?: string | null
	topDoctor?: string | null
	updatedAt: Date
}

export type AppointmentScheduleMV = {
	appointmentId: string
	appointmentPublicId: string
	date: Date
	startTime?: string | null
	durationMinutes?: number | null
	status: string
	type?: string | null
	reason?: string | null
	patientId: string
	patientPublicId: string
	patientName: string
	patientAgeMonths?: number | null
	patientGender?: string | null
	patientPhone?: string | null
	doctorId: string
	doctorPublicId: string
	doctorName: string
	doctorSpecialty?: string | null
	doctorColorCode?: string | null
	serviceId?: string | null
	serviceName?: string | null
	serviceCategory?: string | null
	servicePrice?: number | null
	paymentStatus?: string | null
	totalAmount?: number | null
	amountPaid?: number | null
	clinicId: string
	updatedAt: Date
}

export type PatientGrowthChartMV = {
	patientId: string
	patientPublicId: string
	fullName: string
	gender?: string | null
	dateOfBirth?: Date | null
	ageDays?: number | null
	ageMonths?: number | null
	weight?: number | null
	height?: number | null
	headCircumference?: number | null
	bmi?: number | null
	weightForAgeZ?: number | null
	heightForAgeZ?: number | null
	hcForAgeZ?: number | null
	weightPercentile?: string | null
	heightPercentile?: string | null
	growthStatus?: string | null
	recordedBy?: string | null
	notes?: string | null
	recordedAt: Date
	clinicId: string
	updatedAt: Date
}

export type ImmunizationScheduleMV = {
	patientId: string
	patientPublicId: string
	fullName: string
	dateOfBirth?: Date | null
	ageMonths?: number | null
	immunizationId: string
	vaccineName: string
	doseNumber?: number | null
	totalDoses?: number | null
	administrationDate?: Date | null
	nextDueDate?: Date | null
	status: string
	recommendedAgeDays?: number | null
	isMandatory?: boolean | null
	description?: string | null
	daysOverdue?: number | null
	daysUntilDue?: number | null
	isOverdue: boolean
	administeringDoctor?: string | null
	manufacturer?: string | null
	batchNumber?: string | null
	notes?: string | null
	clinicId: string
	updatedAt: Date
}

export type MedicalRecordsMV = {
	medicalRecordId: string
	medicalRecordPublicId: string
	patientId: string
	patientPublicId: string
	patientName: string
	patientAgeAtDiagnosis?: number | null
	doctorId: string
	doctorPublicId: string
	doctorName: string
	doctorSpecialty?: string | null
	encounterId?: string | null
	encounterDate?: Date | null
	encounterType?: string | null
	diagnosis?: string | null
	treatment?: string | null
	appointmentId?: string | null
	appointmentDate?: Date | null
	appointmentReason?: string | null
	subjective?: string | null
	objective?: string | null
	assessment?: string | null
	plan?: string | null
	symptoms?: string | null
	medications?: string | null
	followUpDate?: Date | null
	isConfidential?: boolean | null
	temperature?: number | null
	heartRate?: number | null
	systolic?: number | null
	diastolic?: number | null
	respiratoryRate?: number | null
	oxygenSaturation?: number | null
	weight?: number | null
	height?: number | null
	prescriptionCount: number
	labTestCount: number
	clinicId: string
	updatedAt: Date
}

export type NotificationsMV = {
	notificationId: string
	notificationPublicId: string
	userId: string
	type: string
	title: string
	message: string
	data?: Record<string, unknown> | null
	isRead: boolean
	priority?: string | null
	actionUrl?: string | null
	createdAt: Date
	expiresAt?: Date | null
	clinicId?: string | null
	clinicName?: string | null
	daysSinceCreated?: number | null
	isExpired: boolean
	relatedPatientId?: string | null
	relatedAppointmentId?: string | null
	relatedDoctorId?: string | null
	updatedAt: Date
}

export type ExpenseAnalysisMV = {
	clinicId: string
	clinicName: string
	expenseCategoryId: string
	expenseCategoryName: string
	expenseCategoryColor?: string | null
	expenseSubcategoryId: string
	expenseSubcategoryName: string
	expenseSubcategoryColor?: string | null
	expenseId: string
	expensePublicId: string
	amount: number
	date: Date
	description?: string | null
	year: number
	month: number
	monthName: string
	quarter: number
	monthlyAverage?: number | null
	categoryPercentage?: number | null
	previousMonthAmount?: number | null
	monthOverMonthChange?: number | null
	updatedAt: Date
}

type Decimal = { valueOf(): string }
